"""fix column seats_patters in table places

Revision ID: d35d4af4cf78
Revises: 22c858234338
Create Date: 2026-05-05 14:12:21.045087

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd35d4af4cf78'
down_revision: Union[str, Sequence[str], None] = '22c858234338'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('places', 'seats_pattern',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('places', 'seats_pattern',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###
